package app.bmri.scripless.model.vo.monitorinvmsg;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 19 06:07:23 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvestorMsgOutgoingViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public InvestorMsgOutgoingViewImpl() {
    }
}
