package app.bmri.scripless.model.vo.monitorinvmsg;

import java.text.DecimalFormat;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 19 06:07:23 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvestorMsgOutgoingViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        StaticSubmit {
            public Object get(InvestorMsgOutgoingViewRowImpl obj) {
                return obj.getStaticSubmit();
            }

            public void put(InvestorMsgOutgoingViewRowImpl obj, Object value) {
                obj.setStaticSubmit((Number)value);
            }
        }
        ,
        StatementSubmit {
            public Object get(InvestorMsgOutgoingViewRowImpl obj) {
                return obj.getStatementSubmit();
            }

            public void put(InvestorMsgOutgoingViewRowImpl obj, Object value) {
                obj.setStatementSubmit((Number)value);
            }
        }
        ,
        ValidationSubmit {
            public Object get(InvestorMsgOutgoingViewRowImpl obj) {
                return obj.getValidationSubmit();
            }

            public void put(InvestorMsgOutgoingViewRowImpl obj, Object value) {
                obj.setValidationSubmit((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(InvestorMsgOutgoingViewRowImpl object);

        public abstract void put(InvestorMsgOutgoingViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int STATICSUBMIT = AttributesEnum.StaticSubmit.index();
    public static final int STATEMENTSUBMIT = AttributesEnum.StatementSubmit.index();
    public static final int VALIDATIONSUBMIT = AttributesEnum.ValidationSubmit.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InvestorMsgOutgoingViewRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute StaticSubmit.
     * @return the StaticSubmit
     */
    public Number getStaticSubmit() {
        return (Number) getAttributeInternal(STATICSUBMIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StaticSubmit.
     * @param value value to set the  StaticSubmit
     */
    public void setStaticSubmit(Number value) {
        setAttributeInternal(STATICSUBMIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StatementSubmit.
     * @return the StatementSubmit
     */
    public Number getStatementSubmit() {
        return (Number)getAttributeInternal(STATEMENTSUBMIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StatementSubmit.
     * @param value value to set the  StatementSubmit
     */
    public void setStatementSubmit(Number value) {
        setAttributeInternal(STATEMENTSUBMIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ValidationSubmit.
     * @return the ValidationSubmit
     */
    public Number getValidationSubmit() {
        return (Number)getAttributeInternal(VALIDATIONSUBMIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ValidationSubmit.
     * @param value value to set the  ValidationSubmit
     */
    public void setValidationSubmit(Number value) {
        setAttributeInternal(VALIDATIONSUBMIT, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
