package app.bmri.scripless.model.vo.anggotabursa;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 12 00:19:15 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AnggotaBursaViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AnggotaBursaViewImpl() {
    }

    /**
     * Returns the variable value for status.
     * @return variable value for status
     */
    public String getstatus() {
        return (String)ensureVariableManager().getVariableValue("status");
    }

    /**
     * Sets <code>value</code> for variable status.
     * @param value value to bind as status
     */
    public void setstatus(String value) {
        ensureVariableManager().setVariableValue("status", value);
    }

    /**
     * Returns the variable value for kodeAb.
     * @return variable value for kodeAb
     */
    public String getkodeAb() {
        return (String)ensureVariableManager().getVariableValue("kodeAb");
    }

    /**
     * Sets <code>value</code> for variable kodeAb.
     * @param value value to bind as kodeAb
     */
    public void setkodeAb(String value) {
        ensureVariableManager().setVariableValue("kodeAb", value);
    }

    /**
     * Returns the variable value for namaAb.
     * @return variable value for namaAb
     */
    public String getnamaAb() {
        return (String)ensureVariableManager().getVariableValue("namaAb");
    }

    /**
     * Sets <code>value</code> for variable namaAb.
     * @param value value to bind as namaAb
     */
    public void setnamaAb(String value) {
        ensureVariableManager().setVariableValue("namaAb", value);
    }

    /**
     * Returns the variable value for sendMethod.
     * @return variable value for sendMethod
     */
    public String getsendMethod() {
        return (String)ensureVariableManager().getVariableValue("sendMethod");
    }

    /**
     * Sets <code>value</code> for variable sendMethod.
     * @param value value to bind as sendMethod
     */
    public void setsendMethod(String value) {
        ensureVariableManager().setVariableValue("sendMethod", value);
    }

    /**
     * Returns the variable value for fileFormat.
     * @return variable value for fileFormat
     */
    public String getfileFormat() {
        return (String)ensureVariableManager().getVariableValue("fileFormat");
    }

    /**
     * Sets <code>value</code> for variable fileFormat.
     * @param value value to bind as fileFormat
     */
    public void setfileFormat(String value) {
        ensureVariableManager().setVariableValue("fileFormat", value);
    }

    /**
     * Returns the variable value for emailAddr.
     * @return variable value for emailAddr
     */
    public String getemailAddr() {
        return (String)ensureVariableManager().getVariableValue("emailAddr");
    }

    /**
     * Sets <code>value</code> for variable emailAddr.
     * @param value value to bind as emailAddr
     */
    public void setemailAddr(String value) {
        ensureVariableManager().setVariableValue("emailAddr", value);
    }

    /**
     * Returns the variable value for ftpUser.
     * @return variable value for ftpUser
     */
    public String getftpUser() {
        return (String)ensureVariableManager().getVariableValue("ftpUser");
    }

    /**
     * Sets <code>value</code> for variable ftpUser.
     * @param value value to bind as ftpUser
     */
    public void setftpUser(String value) {
        ensureVariableManager().setVariableValue("ftpUser", value);
    }

    /**
     * Returns the variable value for ftpPass.
     * @return variable value for ftpPass
     */
    public String getftpPass() {
        return (String)ensureVariableManager().getVariableValue("ftpPass");
    }

    /**
     * Sets <code>value</code> for variable ftpPass.
     * @param value value to bind as ftpPass
     */
    public void setftpPass(String value) {
        ensureVariableManager().setVariableValue("ftpPass", value);
    }
}
