package app.bmri.scripless.model.vo.anggotabursa;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 12 00:19:15 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AnggotaBursaViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        KodeAb {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getKodeAb();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setKodeAb((String)value);
            }
        }
        ,
        NamaAb {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getNamaAb();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setNamaAb((String)value);
            }
        }
        ,
        SendMethod {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getSendMethod();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setSendMethod((String)value);
            }
        }
        ,
        FileFormat {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getFileFormat();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setFileFormat((String)value);
            }
        }
        ,
        EmailAddress {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getEmailAddress();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setEmailAddress((String)value);
            }
        }
        ,
        IpAddress {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getIpAddress();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setIpAddress((String)value);
            }
        }
        ,
        FtpUser {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getFtpUser();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setFtpUser((String)value);
            }
        }
        ,
        FtpPasswd {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getFtpPasswd();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setFtpPasswd((String)value);
            }
        }
        ,
        Excp1 {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getExcp1();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setExcp1((String)value);
            }
        }
        ,
        Direktory {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getDirektory();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setDirektory((String)value);
            }
        }
        ,
        Excp2 {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getExcp2();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setExcp2((String)value);
            }
        }
        ,
        FileSize {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getFileSize();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setFileSize((String)value);
            }
        }
        ,
        Interval {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getInterval();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setInterval((Number)value);
            }
        }
        ,
        NextSchd {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getNextSchd();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setNextSchd((Date)value);
            }
        }
        ,
        NoRekening {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getNoRekening();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setNoRekening((String)value);
            }
        }
        ,
        Port {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getPort();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setPort((Number)value);
            }
        }
        ,
        SerialNo {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getSerialNo();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setSerialNo((String)value);
            }
        }
        ,
        WsPasswd {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getWsPasswd();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setWsPasswd((String)value);
            }
        }
        ,
        WsUser {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getWsUser();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setWsUser((String)value);
            }
        }
        ,
        RowStatus {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getRowStatus();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setRowStatus((Integer)value);
            }
        }
        ,
        AbFileFormatLov1 {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getAbFileFormatLov1();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AbSendMethodLov1 {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getAbSendMethodLov1();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AbStatusAktifLov1 {
            public Object get(AnggotaBursaViewRowImpl obj) {
                return obj.getAbStatusAktifLov1();
            }

            public void put(AnggotaBursaViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(AnggotaBursaViewRowImpl object);

        public abstract void put(AnggotaBursaViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int KODEAB = AttributesEnum.KodeAb.index();
    public static final int NAMAAB = AttributesEnum.NamaAb.index();
    public static final int SENDMETHOD = AttributesEnum.SendMethod.index();
    public static final int FILEFORMAT = AttributesEnum.FileFormat.index();
    public static final int EMAILADDRESS = AttributesEnum.EmailAddress.index();
    public static final int IPADDRESS = AttributesEnum.IpAddress.index();
    public static final int FTPUSER = AttributesEnum.FtpUser.index();
    public static final int FTPPASSWD = AttributesEnum.FtpPasswd.index();
    public static final int EXCP1 = AttributesEnum.Excp1.index();
    public static final int DIREKTORY = AttributesEnum.Direktory.index();
    public static final int EXCP2 = AttributesEnum.Excp2.index();
    public static final int FILESIZE = AttributesEnum.FileSize.index();
    public static final int INTERVAL = AttributesEnum.Interval.index();
    public static final int NEXTSCHD = AttributesEnum.NextSchd.index();
    public static final int NOREKENING = AttributesEnum.NoRekening.index();
    public static final int PORT = AttributesEnum.Port.index();
    public static final int SERIALNO = AttributesEnum.SerialNo.index();
    public static final int WSPASSWD = AttributesEnum.WsPasswd.index();
    public static final int WSUSER = AttributesEnum.WsUser.index();
    public static final int ROWSTATUS = AttributesEnum.RowStatus.index();
    public static final int ABFILEFORMATLOV1 = AttributesEnum.AbFileFormatLov1.index();
    public static final int ABSENDMETHODLOV1 = AttributesEnum.AbSendMethodLov1.index();
    public static final int ABSTATUSAKTIFLOV1 = AttributesEnum.AbStatusAktifLov1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AnggotaBursaViewRowImpl() {
    }

    /**
     * Gets AnggotaBursa1 entity object.
     * @return the AnggotaBursa1
     */
    public EntityImpl getAnggotaBursa1() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for KODE_AB using the alias name KodeAb.
     * @return the KODE_AB
     */
    public String getKodeAb() {
        return (String) getAttributeInternal(KODEAB);
    }

    /**
     * Sets <code>value</code> as attribute value for KODE_AB using the alias name KodeAb.
     * @param value value to set the KODE_AB
     */
    public void setKodeAb(String value) {
        setAttributeInternal(KODEAB, value);
    }

    /**
     * Gets the attribute value for NAMA_AB using the alias name NamaAb.
     * @return the NAMA_AB
     */
    public String getNamaAb() {
        return (String) getAttributeInternal(NAMAAB);
    }

    /**
     * Sets <code>value</code> as attribute value for NAMA_AB using the alias name NamaAb.
     * @param value value to set the NAMA_AB
     */
    public void setNamaAb(String value) {
        setAttributeInternal(NAMAAB, value);
    }

    /**
     * Gets the attribute value for SEND_METHOD using the alias name SendMethod.
     * @return the SEND_METHOD
     */
    public String getSendMethod() {
        return (String) getAttributeInternal(SENDMETHOD);
    }

    /**
     * Sets <code>value</code> as attribute value for SEND_METHOD using the alias name SendMethod.
     * @param value value to set the SEND_METHOD
     */
    public void setSendMethod(String value) {
        setAttributeInternal(SENDMETHOD, value);
    }

    /**
     * Gets the attribute value for FILE_FORMAT using the alias name FileFormat.
     * @return the FILE_FORMAT
     */
    public String getFileFormat() {
        return (String) getAttributeInternal(FILEFORMAT);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_FORMAT using the alias name FileFormat.
     * @param value value to set the FILE_FORMAT
     */
    public void setFileFormat(String value) {
        setAttributeInternal(FILEFORMAT, value);
    }

    /**
     * Gets the attribute value for EMAIL_ADDRESS using the alias name EmailAddress.
     * @return the EMAIL_ADDRESS
     */
    public String getEmailAddress() {
        return (String) getAttributeInternal(EMAILADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL_ADDRESS using the alias name EmailAddress.
     * @param value value to set the EMAIL_ADDRESS
     */
    public void setEmailAddress(String value) {
        setAttributeInternal(EMAILADDRESS, value);
    }

    /**
     * Gets the attribute value for IP_ADDRESS using the alias name IpAddress.
     * @return the IP_ADDRESS
     */
    public String getIpAddress() {
        return (String) getAttributeInternal(IPADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for IP_ADDRESS using the alias name IpAddress.
     * @param value value to set the IP_ADDRESS
     */
    public void setIpAddress(String value) {
        setAttributeInternal(IPADDRESS, value);
    }

    /**
     * Gets the attribute value for FTP_USER using the alias name FtpUser.
     * @return the FTP_USER
     */
    public String getFtpUser() {
        return (String) getAttributeInternal(FTPUSER);
    }

    /**
     * Sets <code>value</code> as attribute value for FTP_USER using the alias name FtpUser.
     * @param value value to set the FTP_USER
     */
    public void setFtpUser(String value) {
        setAttributeInternal(FTPUSER, value);
    }

    /**
     * Gets the attribute value for FTP_PASSWD using the alias name FtpPasswd.
     * @return the FTP_PASSWD
     */
    public String getFtpPasswd() {
        return (String) getAttributeInternal(FTPPASSWD);
    }

    /**
     * Sets <code>value</code> as attribute value for FTP_PASSWD using the alias name FtpPasswd.
     * @param value value to set the FTP_PASSWD
     */
    public void setFtpPasswd(String value) {
        setAttributeInternal(FTPPASSWD, value);
    }

    /**
     * Gets the attribute value for EXCP1 using the alias name Excp1.
     * @return the EXCP1
     */
    public String getExcp1() {
        return (String) getAttributeInternal(EXCP1);
    }

    /**
     * Sets <code>value</code> as attribute value for EXCP1 using the alias name Excp1.
     * @param value value to set the EXCP1
     */
    public void setExcp1(String value) {
        setAttributeInternal(EXCP1, value);
    }

    /**
     * Gets the attribute value for DIREKTORY using the alias name Direktory.
     * @return the DIREKTORY
     */
    public String getDirektory() {
        return (String) getAttributeInternal(DIREKTORY);
    }

    /**
     * Sets <code>value</code> as attribute value for DIREKTORY using the alias name Direktory.
     * @param value value to set the DIREKTORY
     */
    public void setDirektory(String value) {
        setAttributeInternal(DIREKTORY, value);
    }

    /**
     * Gets the attribute value for EXCP2 using the alias name Excp2.
     * @return the EXCP2
     */
    public String getExcp2() {
        return (String) getAttributeInternal(EXCP2);
    }

    /**
     * Sets <code>value</code> as attribute value for EXCP2 using the alias name Excp2.
     * @param value value to set the EXCP2
     */
    public void setExcp2(String value) {
        setAttributeInternal(EXCP2, value);
    }

    /**
     * Gets the attribute value for FILE_SIZE using the alias name FileSize.
     * @return the FILE_SIZE
     */
    public String getFileSize() {
        return (String) getAttributeInternal(FILESIZE);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_SIZE using the alias name FileSize.
     * @param value value to set the FILE_SIZE
     */
    public void setFileSize(String value) {
        setAttributeInternal(FILESIZE, value);
    }

    /**
     * Gets the attribute value for INTERVAL using the alias name Interval.
     * @return the INTERVAL
     */
    public Number getInterval() {
        return (Number) getAttributeInternal(INTERVAL);
    }

    /**
     * Sets <code>value</code> as attribute value for INTERVAL using the alias name Interval.
     * @param value value to set the INTERVAL
     */
    public void setInterval(Number value) {
        setAttributeInternal(INTERVAL, value);
    }

    /**
     * Gets the attribute value for NEXT_SCHD using the alias name NextSchd.
     * @return the NEXT_SCHD
     */
    public Date getNextSchd() {
        return (Date) getAttributeInternal(NEXTSCHD);
    }

    /**
     * Sets <code>value</code> as attribute value for NEXT_SCHD using the alias name NextSchd.
     * @param value value to set the NEXT_SCHD
     */
    public void setNextSchd(Date value) {
        setAttributeInternal(NEXTSCHD, value);
    }

    /**
     * Gets the attribute value for NO_REKENING using the alias name NoRekening.
     * @return the NO_REKENING
     */
    public String getNoRekening() {
        return (String) getAttributeInternal(NOREKENING);
    }

    /**
     * Sets <code>value</code> as attribute value for NO_REKENING using the alias name NoRekening.
     * @param value value to set the NO_REKENING
     */
    public void setNoRekening(String value) {
        setAttributeInternal(NOREKENING, value);
    }

    /**
     * Gets the attribute value for PORT using the alias name Port.
     * @return the PORT
     */
    public Number getPort() {
        return (Number) getAttributeInternal(PORT);
    }

    /**
     * Sets <code>value</code> as attribute value for PORT using the alias name Port.
     * @param value value to set the PORT
     */
    public void setPort(Number value) {
        setAttributeInternal(PORT, value);
    }

    /**
     * Gets the attribute value for SERIAL_NO using the alias name SerialNo.
     * @return the SERIAL_NO
     */
    public String getSerialNo() {
        return (String) getAttributeInternal(SERIALNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SERIAL_NO using the alias name SerialNo.
     * @param value value to set the SERIAL_NO
     */
    public void setSerialNo(String value) {
        setAttributeInternal(SERIALNO, value);
    }

    /**
     * Gets the attribute value for WS_PASSWD using the alias name WsPasswd.
     * @return the WS_PASSWD
     */
    public String getWsPasswd() {
        return (String) getAttributeInternal(WSPASSWD);
    }

    /**
     * Sets <code>value</code> as attribute value for WS_PASSWD using the alias name WsPasswd.
     * @param value value to set the WS_PASSWD
     */
    public void setWsPasswd(String value) {
        setAttributeInternal(WSPASSWD, value);
    }

    /**
     * Gets the attribute value for WS_USER using the alias name WsUser.
     * @return the WS_USER
     */
    public String getWsUser() {
        return (String) getAttributeInternal(WSUSER);
    }

    /**
     * Sets <code>value</code> as attribute value for WS_USER using the alias name WsUser.
     * @param value value to set the WS_USER
     */
    public void setWsUser(String value) {
        setAttributeInternal(WSUSER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RowStatus.
     * @return the RowStatus
     */
    public Integer getRowStatus() {
        byte entityState = this.getEntity(0).getEntityState();
        return new Integer(entityState);
        //return (Integer) getAttributeInternal(ROWSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RowStatus.
     * @param value value to set the  RowStatus
     */
    public void setRowStatus(Integer value) {
        setAttributeInternal(ROWSTATUS, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AbFileFormatLov1.
     */
    public RowSet getAbFileFormatLov1() {
        return (RowSet)getAttributeInternal(ABFILEFORMATLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AbSendMethodLov1.
     */
    public RowSet getAbSendMethodLov1() {
        return (RowSet)getAttributeInternal(ABSENDMETHODLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AbStatusAktifLov1.
     */
    public RowSet getAbStatusAktifLov1() {
        return (RowSet)getAttributeInternal(ABSTATUSAKTIFLOV1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
