package app.bmri.scripless.model.vo.useraccessmenu;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 16 12:50:12 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MenuItemsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MenuItemsViewImpl() {
    }

    /**
     * Returns the bind variable value for usrNameLogin.
     * @return bind variable value for usrNameLogin
     */
    public String getusrNameLogin() {
        return (String)getNamedWhereClauseParam("usrNameLogin");
    }

    /**
     * Sets <code>value</code> for bind variable usrNameLogin.
     * @param value value to bind as usrNameLogin
     */
    public void setusrNameLogin(String value) {
        setNamedWhereClauseParam("usrNameLogin", value);
    }
}
