package app.bmri.scripless.model.vo.useraccessmenu;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 16 12:42:44 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserAccessRolesViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public UserAccessRolesViewImpl() {
    }

    /**
     * Returns the bind variable value for userNameLogin.
     * @return bind variable value for userNameLogin
     */
    public String getuserNameLogin() {
        return (String)getNamedWhereClauseParam("userNameLogin");
    }

    /**
     * Sets <code>value</code> for bind variable userNameLogin.
     * @param value value to bind as userNameLogin
     */
    public void setuserNameLogin(String value) {
        setNamedWhereClauseParam("userNameLogin", value);
    }
}
