package app.bmri.scripless.model.vo.uploadstatic;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 10 02:48:56 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BejstatStgViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BejstatStgViewImpl() {
    }
}
