package app.bmri.scripless.model.vo.uploadstatic;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 06 22:09:51 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StaticTmpViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StaticTmpViewImpl() {
    }
}
