package app.bmri.scripless.model.am.client;

import app.bmri.scripless.model.am.common.AdminModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 21 21:16:32 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AdminModuleClient extends ApplicationModuleImpl implements AdminModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AdminModuleClient() {
    }

    public void setLoginToSession_AdminModule(String key, String val) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setLoginToSession_AdminModule",new String [] {"java.lang.String","java.lang.String"},new Object[] {key, val});
        return;
    }
}
