package app.bmri.scripless.model.am.client;

import app.bmri.scripless.model.am.common.BrokerModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 16 12:33:45 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BrokerModuleClient extends ApplicationModuleImpl implements BrokerModule {
    /**
     * This is the default constructor (do not remove).
     */
    public BrokerModuleClient() {
    }

    public void setLoginToSession_BrokerModule(String key, String val) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setLoginToSession_BrokerModule",new String [] {"java.lang.String","java.lang.String"},new Object[] {key, val});
        return;
    }
}
