package app.bmri.scripless.model.am.client;

import app.bmri.scripless.model.am.common.InvestorModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 16 12:34:08 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvestorModuleClient extends ApplicationModuleImpl implements InvestorModule {
    /**
     * This is the default constructor (do not remove).
     */
    public InvestorModuleClient() {
    }

    public void setLoginToSession_InvestorModule(String key, String val) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setLoginToSession_InvestorModule",new String [] {"java.lang.String","java.lang.String"},new Object[] {key, val});
        return;
    }
}
