package app.bmri.scripless.model.am.client;

import app.bmri.scripless.model.am.common.SecurityModule;

import java.util.Map;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 16 12:41:25 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SecurityModuleClient extends ApplicationModuleImpl implements SecurityModule {
    private static final long serialVersionUID = 1L;

    /**
     * This is the default constructor (do not remove).
     */
    public SecurityModuleClient() {
    }

    public Map authenticateUser(String userLogin, String userPassword) {
        Object _ret =
            this.riInvokeExportedMethod(this,"authenticateUser",new String [] {"java.lang.String","java.lang.String"},new Object[] {userLogin, userPassword});
        return (Map)_ret;
    }
}
