package app.bmri.scripless.model.vo.configparam;

import app.bmri.scripless.model.eo.configparam.JsfConfigsImpl;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 08 09:30:55 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class JsfConfigsViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ConfigId {
            public Object get(JsfConfigsViewRowImpl obj) {
                return obj.getConfigId();
            }

            public void put(JsfConfigsViewRowImpl obj, Object value) {
                obj.setConfigId((DBSequence)value);
            }
        }
        ,
        ConfigDesc {
            public Object get(JsfConfigsViewRowImpl obj) {
                return obj.getConfigDesc();
            }

            public void put(JsfConfigsViewRowImpl obj, Object value) {
                obj.setConfigDesc((String)value);
            }
        }
        ,
        ConfigKey {
            public Object get(JsfConfigsViewRowImpl obj) {
                return obj.getConfigKey();
            }

            public void put(JsfConfigsViewRowImpl obj, Object value) {
                obj.setConfigKey((String)value);
            }
        }
        ,
        ConfigType {
            public Object get(JsfConfigsViewRowImpl obj) {
                return obj.getConfigType();
            }

            public void put(JsfConfigsViewRowImpl obj, Object value) {
                obj.setConfigType((String)value);
            }
        }
        ,
        ConfigValue {
            public Object get(JsfConfigsViewRowImpl obj) {
                return obj.getConfigValue();
            }

            public void put(JsfConfigsViewRowImpl obj, Object value) {
                obj.setConfigValue((String)value);
            }
        }
        ,
        ConfigVersion {
            public Object get(JsfConfigsViewRowImpl obj) {
                return obj.getConfigVersion();
            }

            public void put(JsfConfigsViewRowImpl obj, Object value) {
                obj.setConfigVersion((Number)value);
            }
        }
        ,
        RowID {
            public Object get(JsfConfigsViewRowImpl obj) {
                return obj.getRowID();
            }

            public void put(JsfConfigsViewRowImpl obj, Object value) {
                obj.setRowID((RowID)value);
            }
        }
        ,
        RowStatus {
            public Object get(JsfConfigsViewRowImpl obj) {
                return obj.getRowStatus();
            }

            public void put(JsfConfigsViewRowImpl obj, Object value) {
                obj.setRowStatus((Integer)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(JsfConfigsViewRowImpl object);

        public abstract void put(JsfConfigsViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int CONFIGID = AttributesEnum.ConfigId.index();
    public static final int CONFIGDESC = AttributesEnum.ConfigDesc.index();
    public static final int CONFIGKEY = AttributesEnum.ConfigKey.index();
    public static final int CONFIGTYPE = AttributesEnum.ConfigType.index();
    public static final int CONFIGVALUE = AttributesEnum.ConfigValue.index();
    public static final int CONFIGVERSION = AttributesEnum.ConfigVersion.index();
    public static final int ROWID = AttributesEnum.RowID.index();
    public static final int ROWSTATUS = AttributesEnum.RowStatus.index();

    /**
     * This is the default constructor (do not remove).
     */
    public JsfConfigsViewRowImpl() {
    }

    /**
     * Gets JsfConfigs entity object.
     * @return the JsfConfigs
     */
    public JsfConfigsImpl getJsfConfigs() {
        return (JsfConfigsImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for CONFIG_ID using the alias name ConfigId.
     * @return the CONFIG_ID
     */
    public DBSequence getConfigId() {
        return (DBSequence)getAttributeInternal(CONFIGID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONFIG_ID using the alias name ConfigId.
     * @param value value to set the CONFIG_ID
     */
    public void setConfigId(DBSequence value) {
        setAttributeInternal(CONFIGID, value);
    }

    /**
     * Gets the attribute value for CONFIG_DESC using the alias name ConfigDesc.
     * @return the CONFIG_DESC
     */
    public String getConfigDesc() {
        return (String) getAttributeInternal(CONFIGDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for CONFIG_DESC using the alias name ConfigDesc.
     * @param value value to set the CONFIG_DESC
     */
    public void setConfigDesc(String value) {
        setAttributeInternal(CONFIGDESC, value);
    }

    /**
     * Gets the attribute value for CONFIG_KEY using the alias name ConfigKey.
     * @return the CONFIG_KEY
     */
    public String getConfigKey() {
        return (String) getAttributeInternal(CONFIGKEY);
    }

    /**
     * Sets <code>value</code> as attribute value for CONFIG_KEY using the alias name ConfigKey.
     * @param value value to set the CONFIG_KEY
     */
    public void setConfigKey(String value) {
        setAttributeInternal(CONFIGKEY, value);
    }

    /**
     * Gets the attribute value for CONFIG_TYPE using the alias name ConfigType.
     * @return the CONFIG_TYPE
     */
    public String getConfigType() {
        return (String) getAttributeInternal(CONFIGTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONFIG_TYPE using the alias name ConfigType.
     * @param value value to set the CONFIG_TYPE
     */
    public void setConfigType(String value) {
        setAttributeInternal(CONFIGTYPE, value);
    }

    /**
     * Gets the attribute value for CONFIG_VALUE using the alias name ConfigValue.
     * @return the CONFIG_VALUE
     */
    public String getConfigValue() {
        return (String) getAttributeInternal(CONFIGVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONFIG_VALUE using the alias name ConfigValue.
     * @param value value to set the CONFIG_VALUE
     */
    public void setConfigValue(String value) {
        setAttributeInternal(CONFIGVALUE, value);
    }

    /**
     * Gets the attribute value for CONFIG_VERSION using the alias name ConfigVersion.
     * @return the CONFIG_VERSION
     */
    public Number getConfigVersion() {
        return (Number) getAttributeInternal(CONFIGVERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for CONFIG_VERSION using the alias name ConfigVersion.
     * @param value value to set the CONFIG_VERSION
     */
    public void setConfigVersion(Number value) {
        setAttributeInternal(CONFIGVERSION, value);
    }

    /**
     * Gets the attribute value for ROWID using the alias name RowID.
     * @return the ROWID
     */
    public RowID getRowID() {
        return (RowID) getAttributeInternal(ROWID);
    }

    /**
     * Sets <code>value</code> as attribute value for ROWID using the alias name RowID.
     * @param value value to set the ROWID
     */
    public void setRowID(RowID value) {
        setAttributeInternal(ROWID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RowStatus.
     * @return the RowStatus
     */
    public Integer getRowStatus() {
        byte entityState = this.getEntity(0).getEntityState();
        return new Integer(entityState);
        //return (Integer) getAttributeInternal(ROWSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RowStatus.
     * @param value value to set the  RowStatus
     */
    public void setRowStatus(Integer value) {
        setAttributeInternal(ROWSTATUS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
