package app.bmri.scripless.model.vo.uploadstmt;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 09 13:21:45 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BejstmtStgViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BejstmtStgViewImpl() {
    }
}
