package app.bmri.scripless.model.am;

import app.bmri.scripless.adfextensions.CustomApplicationModuleImpl;

import app.bmri.scripless.model.am.common.AdminModule;

import app.bmri.scripless.model.vo.useraccessadminister.ChangeUserPasswordViewImpl;

import oracle.jbo.Row;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 21 21:15:58 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AdminModuleImpl extends CustomApplicationModuleImpl implements AdminModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AdminModuleImpl() {
    }

    public void changePassword(String userId, String newPassword) {
        ViewObjectImpl user = getChangeUserPasswordView1();
        ViewCriteria uc = user.createViewCriteria();
        ViewCriteriaRow userVcr = uc.createViewCriteriaRow();
        userVcr.setAttribute("UserName", "=" + userId);
        uc.addElement(userVcr);
        user.applyViewCriteria(uc);
        user.executeQuery();

        Row userRow = user.first();
        userRow.setAttribute("Password", newPassword);
        getDBTransaction().commit();
    }
        
    public void setLoginToSession_AdminModule(String key, String val) {
        this.setLoginToSession(key, val);
    }
    
    /**
     * Container's getter for MenuAdminView1.
     * @return MenuAdminView1
     */
    public ViewObjectImpl getMenuAdminView1() {
        return (ViewObjectImpl)findViewObject("MenuAdminView1");
    }

    /**
     * Container's getter for MenuItemsAdminView1.
     * @return MenuItemsAdminView1
     */
    public ViewObjectImpl getMenuItemsAdminView1() {
        return (ViewObjectImpl)findViewObject("MenuItemsAdminView1");
    }

    /**
     * Container's getter for RolesAdminView1.
     * @return RolesAdminView1
     */
    public ViewObjectImpl getRolesAdminView1() {
        return (ViewObjectImpl)findViewObject("RolesAdminView1");
    }

    /**
     * Container's getter for RoleMenuItemsAdminView1.
     * @return RoleMenuItemsAdminView1
     */
    public ViewObjectImpl getRoleMenuItemsAdminView1() {
        return (ViewObjectImpl)findViewObject("RoleMenuItemsAdminView1");
    }

    /**
     * Container's getter for UserAccessAdminView1.
     * @return UserAccessAdminView1
     */
    public ViewObjectImpl getUserAccessAdminView1() {
        return (ViewObjectImpl)findViewObject("UserAccessAdminView1");
    }

    /**
     * Container's getter for UserAccessRolesAdminView1.
     * @return UserAccessRolesAdminView1
     */
    public ViewObjectImpl getUserAccessRolesAdminView1() {
        return (ViewObjectImpl)findViewObject("UserAccessRolesAdminView1");
    }

    /**
     * Container's getter for MenuItemsShuttleView1.
     * @return MenuItemsShuttleView1
     */
    public ViewObjectImpl getMenuItemsShuttleView1() {
        return (ViewObjectImpl)findViewObject("MenuItemsShuttleView1");
    }

    /**
     * Container's getter for RolesShuttleView1.
     * @return RolesShuttleView1
     */
    public ViewObjectImpl getRolesShuttleView1() {
        return (ViewObjectImpl)findViewObject("RolesShuttleView1");
    }

    /**
     * Container's getter for MitMenAdminFkLink1.
     * @return MitMenAdminFkLink1
     */
    public ViewLinkImpl getMitMenAdminFkLink1() {
        return (ViewLinkImpl)findViewLink("MitMenAdminFkLink1");
    }

    /**
     * Container's getter for RolesRmiAdminFkLink1.
     * @return RolesRmiAdminFkLink1
     */
    public ViewLinkImpl getRolesRmiAdminFkLink1() {
        return (ViewLinkImpl)findViewLink("RolesRmiAdminFkLink1");
    }

    /**
     * Container's getter for UserAccessUserAccessRolesFkLink1.
     * @return UserAccessUserAccessRolesFkLink1
     */
    public ViewLinkImpl getUserAccessUserAccessRolesFkLink1() {
        return (ViewLinkImpl)findViewLink("UserAccessUserAccessRolesFkLink1");
    }

    /**
     * Container's getter for ChangeUserPasswordView1.
     * @return ChangeUserPasswordView1
     */
    public ViewObjectImpl getChangeUserPasswordView1() {
        return (ViewObjectImpl)findViewObject("ChangeUserPasswordView1");
    }

    /**
     * Container's getter for JsfConfigsView1.
     * @return JsfConfigsView1
     */
    public ViewObjectImpl getJsfConfigsView1() {
        return (ViewObjectImpl)findViewObject("JsfConfigsView1");
    }
}
