package app.bmri.scripless.model.am;

import app.bmri.scripless.adfextensions.CustomApplicationModuleImpl;
import app.bmri.scripless.model.am.common.BrokerModule;
import app.bmri.scripless.model.vo.anggotabursa.AnggotaBursaViewImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 16 12:32:09 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BrokerModuleImpl extends CustomApplicationModuleImpl implements BrokerModule {
    /**
     * This is the default constructor (do not remove).
     */
    public BrokerModuleImpl() {
    }
        
    public void setLoginToSession_BrokerModule(String key, String val) {
        this.setLoginToSession(key, val);
    }

    /**
     * Container's getter for AnggotaBursaView1.
     * @return AnggotaBursaView1
     */
    public AnggotaBursaViewImpl getAnggotaBursaView1() {
        return (AnggotaBursaViewImpl)findViewObject("AnggotaBursaView1");
    }

    /**
     * Container's getter for InvestorView1.
     * @return InvestorView1
     */
    public ViewObjectImpl getInvestorView1() {
        return (ViewObjectImpl)findViewObject("InvestorView1");
    }

    /**
     * Container's getter for Filestmt2sentView1.
     * @return Filestmt2sentView1
     */
    public ViewObjectImpl getFilestmt2sentView1() {
        return (ViewObjectImpl)findViewObject("Filestmt2sentView1");
    }

    /**
     * Container's getter for FileSendingQView1.
     * @return FileSendingQView1
     */
    public ViewObjectImpl getFileSendingQView1() {
        return (ViewObjectImpl)findViewObject("FileSendingQView1");
    }

    /**
     * Container's getter for Filestmt2sentFileSendingQViewLink1.
     * @return Filestmt2sentFileSendingQViewLink1
     */
    public ViewLinkImpl getFilestmt2sentFileSendingQViewLink1() {
        return (ViewLinkImpl)findViewLink("Filestmt2sentFileSendingQViewLink1");
    }
}
