package app.bmri.scripless.model.am;


import app.bmri.scripless.adfextensions.CustomApplicationModuleImpl;

import app.bmri.scripless.model.am.common.InvestorModule;
import app.bmri.scripless.model.vo.terminalmonitor.ConnectTChartViewImpl;
import app.bmri.scripless.model.vo.uploadstatic.BejstatStgViewImpl;
import app.bmri.scripless.model.vo.uploadstatic.StaticTmpViewImpl;
import app.bmri.scripless.model.vo.uploadstmt.BejstmtStgViewImpl;
import app.bmri.scripless.model.vo.uploadstmt.StatementTmpViewImpl;
import app.bmri.scripless.model.vo.valinvestor.ValidationMsgViewImpl;
import app.bmri.scripless.model.vo.valinvestor.ValidationTmpViewImpl;

import oracle.jbo.VariableValueManager;
import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 03 10:27:18 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvestorModuleImpl extends CustomApplicationModuleImpl implements InvestorModule {
    /**
     * This is the default constructor (do not remove).
     */
    public InvestorModuleImpl() {
    }
        
    public void setLoginToSession_InvestorModule(String key, String val) {
        this.setLoginToSession(key, val);
    }

    /**
     * Container's getter for ValidationMsgView1.
     * @return ValidationMsgView1
     */
    public ViewObjectImpl getValidationMsgView1() {
        return (ViewObjectImpl)findViewObject("ValidationMsgView1");
    }

    /**
     * Container's getter for ValidationTmpView1.
     * @return ValidationTmpView1
     */
    public ViewObjectImpl getValidationTmpView1() {
        return (ViewObjectImpl)findViewObject("ValidationTmpView1");
    }

    /**
     * Container's getter for StatementTmpView1.
     * @return StatementTmpView1
     */
    public ViewObjectImpl getStatementTmpView1() {
        return (ViewObjectImpl)findViewObject("StatementTmpView1");
    }

    /**
     * Container's getter for StaticTmpView1.
     * @return StaticTmpView1
     */
    public ViewObjectImpl getStaticTmpView1() {
        return (ViewObjectImpl)findViewObject("StaticTmpView1");
    }

    /**
     * Container's getter for ResendStatementView1.
     * @return ResendStatementView1
     */
    public ViewObjectImpl getResendStatementView1() {
        return (ViewObjectImpl)findViewObject("ResendStatementView1");
    }

    /**
     * Container's getter for ConnectTView1.
     * @return ConnectTView1
     */
    public ViewObjectImpl getConnectTView1() {
        return (ViewObjectImpl)findViewObject("ConnectTView1");
    }

    /**
     * Container's getter for BejstmtStgView1.
     * @return BejstmtStgView1
     */
    public ViewObjectImpl getBejstmtStgView1() {
        return (ViewObjectImpl)findViewObject("BejstmtStgView1");
    }

    /**
     * Container's getter for BejstatStgView1.
     * @return BejstatStgView1
     */
    public BejstatStgViewImpl getBejstatStgView1() {
        return (BejstatStgViewImpl)findViewObject("BejstatStgView1");
    }

    /**
     * Container's getter for ConnectTChartView1.
     * @return ConnectTChartView1
     */
    public ViewObjectImpl getConnectTChartView1() {
        return (ViewObjectImpl)findViewObject("ConnectTChartView1");
    }

    /**
     * Container's getter for InvestorMsgIncomingView1.
     * @return InvestorMsgIncomingView1
     */
    public ViewObjectImpl getInvestorMsgIncomingView1() {
        return (ViewObjectImpl)findViewObject("InvestorMsgIncomingView1");
    }

    /**
     * Container's getter for InvestorMsgOutgoingView1.
     * @return InvestorMsgOutgoingView1
     */
    public ViewObjectImpl getInvestorMsgOutgoingView1() {
        return (ViewObjectImpl)findViewObject("InvestorMsgOutgoingView1");
    }

    /**
     * Container's getter for FileSendingQEomView1.
     * @return FileSendingQEomView1
     */
    public ViewObjectImpl getFileSendingQEomView1() {
        return (ViewObjectImpl)findViewObject("FileSendingQEomView1");
    }
}
