package app.bmri.scripless.model.am;

import app.bmri.scripless.adfextensions.CustomApplicationModuleImpl;

import app.bmri.scripless.model.am.common.KSEIModule;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 09 02:11:45 ICT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KSEIModuleImpl extends CustomApplicationModuleImpl implements KSEIModule {
    /**
     * This is the default constructor (do not remove).
     */
    public KSEIModuleImpl() {
    }
        
    public void setLoginToSession_KSEIModule(String key, String val) {
        this.setLoginToSession(key, val);
    }

    /**
     * Container's getter for FileTransmisionView1.
     * @return FileTransmisionView1
     */
    public ViewObjectImpl getFileTransmisionView1() {
        return (ViewObjectImpl)findViewObject("FileTransmisionView1");
    }

    /**
     * Container's getter for StatementKseiView1.
     * @return StatementKseiView1
     */
    public ViewObjectImpl getStatementKseiView1() {
        return (ViewObjectImpl)findViewObject("StatementKseiView1");
    }

    /**
     * Container's getter for BalanceKseiView1.
     * @return BalanceKseiView1
     */
    public ViewObjectImpl getBalanceKseiView1() {
        return (ViewObjectImpl)findViewObject("BalanceKseiView1");
    }

    /**
     * Container's getter for StaticKseiView1.
     * @return StaticKseiView1
     */
    public ViewObjectImpl getStaticKseiView1() {
        return (ViewObjectImpl)findViewObject("StaticKseiView1");
    }
}
