package app.bmri.scripless.model.am;


import app.bmri.scripless.adfextensions.CustomApplicationModuleImpl;
import app.bmri.scripless.model.am.common.SecurityModule;
import app.bmri.scripless.model.vo.useraccessmenu.UserAccessRolesViewImpl;

import java.util.HashMap;
import java.util.Map;
import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;

import org.apache.commons.codec.digest.DigestUtils;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 16 12:39:38 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SecurityModuleImpl extends CustomApplicationModuleImpl implements SecurityModule {
    /**
     * This is the default constructor (do not remove).
     */
    public SecurityModuleImpl() {
    }

    /**
     * Function to find user row by login and password
     * @return map with user data and list of privileges
     */
    public Map authenticateUser(String userLogin, String userPassword) {
        
        Map userData = new HashMap();
        HashMap userAccess = new HashMap();
        
        ViewObjectImpl user = this.getUserAccessView1();
        user.setMaxFetchSize(1);
        user.setNamedWhereClauseParam("userLogin", userLogin);
        /* ENCRYPTED */
        user.setNamedWhereClauseParam("userPassword",DigestUtils.sha1Hex(userPassword));
        
        /* NOT ENCRYPTED
        user.setNamedWhereClauseParam("userPassword",userPassword);
        */
        user.executeQuery();

        if (user.getEstimatedRowCount() > 0) {

            Row userRow = user.first();
            String fullName = (String)userRow.getAttribute("FullName");
            String userNameLogin = (String)userRow.getAttribute("UserName");
            String title = (String)userRow.getAttribute("Title");
                        
            userData.put("FullName", fullName);
            userData.put("Password", userPassword);
            userData.put("UserName", userNameLogin);
            userData.put("Title", title);
            setToSession("UserId", userLogin); // Save Login ID to BC session
            
            //Retrive User Roles
            UserAccessRolesViewImpl groupOfRoles;
            groupOfRoles = (UserAccessRolesViewImpl)this.getUserAccessRolesView1();
            groupOfRoles.setNamedWhereClauseParam("userNameLogin", userNameLogin);
            groupOfRoles.executeQuery();

            while (groupOfRoles.hasNext()) {
                Row privsRow = groupOfRoles.next();
                String roleName = (String)privsRow.getAttribute("Role");
                String userName = (String)privsRow.getAttribute("UserName");
                userAccess.put(roleName, userName);
            }
            
            userData.put("UserAccess", userAccess);
        } else {
            userData.put("FullName", "");
            userData.put("Password", "");
            userData.put("UserName", "INVALID");
            userData.put("Title", "");
        }

        return userData;
    }
    
    /**
     * Container's getter for UserAccessRolesView1.
     * @return UserAccessRolesView1
     */
    public ViewObjectImpl getUserAccessRolesView1() {
        return (ViewObjectImpl)findViewObject("UserAccessRolesView1");
    }

    /**
     * Container's getter for UserAccessView1.
     * @return UserAccessView1
     */
    public ViewObjectImpl getUserAccessView1() {
        return (ViewObjectImpl)findViewObject("UserAccessView1");
    }

    /**
     * Container's getter for MenuItemsView1.
     * @return MenuItemsView1
     */
    public ViewObjectImpl getMenuItemsView1() {
        return (ViewObjectImpl)findViewObject("MenuItemsView1");
    }

}
