package app.bmri.scripless.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 21 21:16:31 ICT 2016
// ---------------------------------------------------------------------
public interface AdminModule extends ApplicationModule {
    void setLoginToSession_AdminModule(String key, String val);
}
