package app.bmri.scripless.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 16 12:33:45 ICT 2016
// ---------------------------------------------------------------------
public interface BrokerModule extends ApplicationModule {
    void setLoginToSession_BrokerModule(String key, String val);
}
