package app.bmri.scripless.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 16 12:34:08 ICT 2016
// ---------------------------------------------------------------------
public interface InvestorModule extends ApplicationModule {
    void setLoginToSession_InvestorModule(String key, String val);
}
