package app.bmri.scripless.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 09 02:13:34 ICT 2020
// ---------------------------------------------------------------------
public interface KSEIModule extends ApplicationModule {
    void setLoginToSession_KSEIModule(String key, String val);
}
