package app.bmri.scripless.model.vo.useraccessadminister;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 21 21:44:58 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ChangeUserPasswordViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ChangeUserPasswordViewImpl() {
    }


}
