package app.bmri.scripless.model.vo.valinvestor;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 04 23:37:43 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ValidationMsgViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ValidationMsgViewImpl() {
    }
}
