package app.bmri.scripless.model.vo.valinvestor;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 04 09:40:33 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ValidationTmpViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ValidationTmpViewImpl() {
    }
}
