package app.bmri.scripless.model.vo.valinvestor;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 04 09:40:33 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ValidationTmpViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Batchref {
            public Object get(ValidationTmpViewRowImpl obj) {
                return obj.getBatchref();
            }

            public void put(ValidationTmpViewRowImpl obj, Object value) {
                obj.setBatchref((String)value);
            }
        }
        ,
        Detailref {
            public Object get(ValidationTmpViewRowImpl obj) {
                return obj.getDetailref();
            }

            public void put(ValidationTmpViewRowImpl obj, Object value) {
                obj.setDetailref((String)value);
            }
        }
        ,
        Participantid {
            public Object get(ValidationTmpViewRowImpl obj) {
                return obj.getParticipantid();
            }

            public void put(ValidationTmpViewRowImpl obj, Object value) {
                obj.setParticipantid((String)value);
            }
        }
        ,
        Sidnumber {
            public Object get(ValidationTmpViewRowImpl obj) {
                return obj.getSidnumber();
            }

            public void put(ValidationTmpViewRowImpl obj, Object value) {
                obj.setSidnumber((String)value);
            }
        }
        ,
        Accountnumber {
            public Object get(ValidationTmpViewRowImpl obj) {
                return obj.getAccountnumber();
            }

            public void put(ValidationTmpViewRowImpl obj, Object value) {
                obj.setAccountnumber((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(ValidationTmpViewRowImpl object);

        public abstract void put(ValidationTmpViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int BATCHREF = AttributesEnum.Batchref.index();
    public static final int DETAILREF = AttributesEnum.Detailref.index();
    public static final int PARTICIPANTID = AttributesEnum.Participantid.index();
    public static final int SIDNUMBER = AttributesEnum.Sidnumber.index();
    public static final int ACCOUNTNUMBER = AttributesEnum.Accountnumber.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ValidationTmpViewRowImpl() {
    }

    /**
     * Gets ValidationTmp entity object.
     * @return the ValidationTmp
     */
    public EntityImpl getValidationTmp() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for BATCHREF using the alias name Batchref.
     * @return the BATCHREF
     */
    public String getBatchref() {
        return (String) getAttributeInternal(BATCHREF);
    }

    /**
     * Sets <code>value</code> as attribute value for BATCHREF using the alias name Batchref.
     * @param value value to set the BATCHREF
     */
    public void setBatchref(String value) {
        setAttributeInternal(BATCHREF, value);
    }

    /**
     * Gets the attribute value for DETAILREF using the alias name Detailref.
     * @return the DETAILREF
     */
    public String getDetailref() {
        return (String) getAttributeInternal(DETAILREF);
    }

    /**
     * Sets <code>value</code> as attribute value for DETAILREF using the alias name Detailref.
     * @param value value to set the DETAILREF
     */
    public void setDetailref(String value) {
        setAttributeInternal(DETAILREF, value);
    }

    /**
     * Gets the attribute value for PARTICIPANTID using the alias name Participantid.
     * @return the PARTICIPANTID
     */
    public String getParticipantid() {
        return (String) getAttributeInternal(PARTICIPANTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PARTICIPANTID using the alias name Participantid.
     * @param value value to set the PARTICIPANTID
     */
    public void setParticipantid(String value) {
        setAttributeInternal(PARTICIPANTID, value);
    }

    /**
     * Gets the attribute value for SIDNUMBER using the alias name Sidnumber.
     * @return the SIDNUMBER
     */
    public String getSidnumber() {
        return (String) getAttributeInternal(SIDNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SIDNUMBER using the alias name Sidnumber.
     * @param value value to set the SIDNUMBER
     */
    public void setSidnumber(String value) {
        setAttributeInternal(SIDNUMBER, value);
    }

    /**
     * Gets the attribute value for ACCOUNTNUMBER using the alias name Accountnumber.
     * @return the ACCOUNTNUMBER
     */
    public String getAccountnumber() {
        return (String) getAttributeInternal(ACCOUNTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCOUNTNUMBER using the alias name Accountnumber.
     * @param value value to set the ACCOUNTNUMBER
     */
    public void setAccountnumber(String value) {
        setAttributeInternal(ACCOUNTNUMBER, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
