package app.bmri.scripless.model.vo.valinvestor;

import app.bmri.scripless.model.eo.valinvestor.ValidationMsgImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 04 23:37:43 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ValidationMsgViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Batchref {
            public Object get(ValidationMsgViewRowImpl obj) {
                return obj.getBatchref();
            }

            public void put(ValidationMsgViewRowImpl obj, Object value) {
                obj.setBatchref((String)value);
            }
        }
        ,
        Detailref {
            public Object get(ValidationMsgViewRowImpl obj) {
                return obj.getDetailref();
            }

            public void put(ValidationMsgViewRowImpl obj, Object value) {
                obj.setDetailref((String)value);
            }
        }
        ,
        Participantid {
            public Object get(ValidationMsgViewRowImpl obj) {
                return obj.getParticipantid();
            }

            public void put(ValidationMsgViewRowImpl obj, Object value) {
                obj.setParticipantid((String)value);
            }
        }
        ,
        Sidnumber {
            public Object get(ValidationMsgViewRowImpl obj) {
                return obj.getSidnumber();
            }

            public void put(ValidationMsgViewRowImpl obj, Object value) {
                obj.setSidnumber((String)value);
            }
        }
        ,
        Accountnumber {
            public Object get(ValidationMsgViewRowImpl obj) {
                return obj.getAccountnumber();
            }

            public void put(ValidationMsgViewRowImpl obj, Object value) {
                obj.setAccountnumber((String)value);
            }
        }
        ,
        CreateTime {
            public Object get(ValidationMsgViewRowImpl obj) {
                return obj.getCreateTime();
            }

            public void put(ValidationMsgViewRowImpl obj, Object value) {
                obj.setCreateTime((Date)value);
            }
        }
        ,
        Ackparticipantid {
            public Object get(ValidationMsgViewRowImpl obj) {
                return obj.getAckparticipantid();
            }

            public void put(ValidationMsgViewRowImpl obj, Object value) {
                obj.setAckparticipantid((String)value);
            }
        }
        ,
        AckTime {
            public Object get(ValidationMsgViewRowImpl obj) {
                return obj.getAckTime();
            }

            public void put(ValidationMsgViewRowImpl obj, Object value) {
                obj.setAckTime((Date)value);
            }
        }
        ,
        Acksidnumber {
            public Object get(ValidationMsgViewRowImpl obj) {
                return obj.getAcksidnumber();
            }

            public void put(ValidationMsgViewRowImpl obj, Object value) {
                obj.setAcksidnumber((String)value);
            }
        }
        ,
        Ackaccountnumber {
            public Object get(ValidationMsgViewRowImpl obj) {
                return obj.getAckaccountnumber();
            }

            public void put(ValidationMsgViewRowImpl obj, Object value) {
                obj.setAckaccountnumber((String)value);
            }
        }
        ,
        Ackinvestorname {
            public Object get(ValidationMsgViewRowImpl obj) {
                return obj.getAckinvestorname();
            }

            public void put(ValidationMsgViewRowImpl obj, Object value) {
                obj.setAckinvestorname((String)value);
            }
        }
        ,
        Ackinvestorid {
            public Object get(ValidationMsgViewRowImpl obj) {
                return obj.getAckinvestorid();
            }

            public void put(ValidationMsgViewRowImpl obj, Object value) {
                obj.setAckinvestorid((String)value);
            }
        }
        ,
        Ackinvestornpwp {
            public Object get(ValidationMsgViewRowImpl obj) {
                return obj.getAckinvestornpwp();
            }

            public void put(ValidationMsgViewRowImpl obj, Object value) {
                obj.setAckinvestornpwp((String)value);
            }
        }
        ,
        Ackinvestorpassport {
            public Object get(ValidationMsgViewRowImpl obj) {
                return obj.getAckinvestorpassport();
            }

            public void put(ValidationMsgViewRowImpl obj, Object value) {
                obj.setAckinvestorpassport((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(ValidationMsgViewRowImpl object);

        public abstract void put(ValidationMsgViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int BATCHREF = AttributesEnum.Batchref.index();
    public static final int DETAILREF = AttributesEnum.Detailref.index();
    public static final int PARTICIPANTID = AttributesEnum.Participantid.index();
    public static final int SIDNUMBER = AttributesEnum.Sidnumber.index();
    public static final int ACCOUNTNUMBER = AttributesEnum.Accountnumber.index();
    public static final int CREATETIME = AttributesEnum.CreateTime.index();
    public static final int ACKPARTICIPANTID = AttributesEnum.Ackparticipantid.index();
    public static final int ACKTIME = AttributesEnum.AckTime.index();
    public static final int ACKSIDNUMBER = AttributesEnum.Acksidnumber.index();
    public static final int ACKACCOUNTNUMBER = AttributesEnum.Ackaccountnumber.index();
    public static final int ACKINVESTORNAME = AttributesEnum.Ackinvestorname.index();
    public static final int ACKINVESTORID = AttributesEnum.Ackinvestorid.index();
    public static final int ACKINVESTORNPWP = AttributesEnum.Ackinvestornpwp.index();
    public static final int ACKINVESTORPASSPORT = AttributesEnum.Ackinvestorpassport.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ValidationMsgViewRowImpl() {
    }

    /**
     * Gets ValidationMsg entity object.
     * @return the ValidationMsg
     */
    public ValidationMsgImpl getValidationMsg() {
        return (ValidationMsgImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for BATCHREF using the alias name Batchref.
     * @return the BATCHREF
     */
    public String getBatchref() {
        return (String) getAttributeInternal(BATCHREF);
    }

    /**
     * Sets <code>value</code> as attribute value for BATCHREF using the alias name Batchref.
     * @param value value to set the BATCHREF
     */
    public void setBatchref(String value) {
        setAttributeInternal(BATCHREF, value);
    }

    /**
     * Gets the attribute value for DETAILREF using the alias name Detailref.
     * @return the DETAILREF
     */
    public String getDetailref() {
        return (String) getAttributeInternal(DETAILREF);
    }

    /**
     * Sets <code>value</code> as attribute value for DETAILREF using the alias name Detailref.
     * @param value value to set the DETAILREF
     */
    public void setDetailref(String value) {
        setAttributeInternal(DETAILREF, value);
    }

    /**
     * Gets the attribute value for PARTICIPANTID using the alias name Participantid.
     * @return the PARTICIPANTID
     */
    public String getParticipantid() {
        return (String) getAttributeInternal(PARTICIPANTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PARTICIPANTID using the alias name Participantid.
     * @param value value to set the PARTICIPANTID
     */
    public void setParticipantid(String value) {
        setAttributeInternal(PARTICIPANTID, value);
    }

    /**
     * Gets the attribute value for SIDNUMBER using the alias name Sidnumber.
     * @return the SIDNUMBER
     */
    public String getSidnumber() {
        return (String) getAttributeInternal(SIDNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SIDNUMBER using the alias name Sidnumber.
     * @param value value to set the SIDNUMBER
     */
    public void setSidnumber(String value) {
        setAttributeInternal(SIDNUMBER, value);
    }

    /**
     * Gets the attribute value for ACCOUNTNUMBER using the alias name Accountnumber.
     * @return the ACCOUNTNUMBER
     */
    public String getAccountnumber() {
        return (String) getAttributeInternal(ACCOUNTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCOUNTNUMBER using the alias name Accountnumber.
     * @param value value to set the ACCOUNTNUMBER
     */
    public void setAccountnumber(String value) {
        setAttributeInternal(ACCOUNTNUMBER, value);
    }

    /**
     * Gets the attribute value for CREATE_TIME using the alias name CreateTime.
     * @return the CREATE_TIME
     */
    public Date getCreateTime() {
        return (Date) getAttributeInternal(CREATETIME);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_TIME using the alias name CreateTime.
     * @param value value to set the CREATE_TIME
     */
    public void setCreateTime(Date value) {
        setAttributeInternal(CREATETIME, value);
    }

    /**
     * Gets the attribute value for ACKPARTICIPANTID using the alias name Ackparticipantid.
     * @return the ACKPARTICIPANTID
     */
    public String getAckparticipantid() {
        return (String) getAttributeInternal(ACKPARTICIPANTID);
    }

    /**
     * Sets <code>value</code> as attribute value for ACKPARTICIPANTID using the alias name Ackparticipantid.
     * @param value value to set the ACKPARTICIPANTID
     */
    public void setAckparticipantid(String value) {
        setAttributeInternal(ACKPARTICIPANTID, value);
    }

    /**
     * Gets the attribute value for ACK_TIME using the alias name AckTime.
     * @return the ACK_TIME
     */
    public Date getAckTime() {
        return (Date) getAttributeInternal(ACKTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for ACK_TIME using the alias name AckTime.
     * @param value value to set the ACK_TIME
     */
    public void setAckTime(Date value) {
        setAttributeInternal(ACKTIME, value);
    }

    /**
     * Gets the attribute value for ACKSIDNUMBER using the alias name Acksidnumber.
     * @return the ACKSIDNUMBER
     */
    public String getAcksidnumber() {
        return (String) getAttributeInternal(ACKSIDNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for ACKSIDNUMBER using the alias name Acksidnumber.
     * @param value value to set the ACKSIDNUMBER
     */
    public void setAcksidnumber(String value) {
        setAttributeInternal(ACKSIDNUMBER, value);
    }

    /**
     * Gets the attribute value for ACKACCOUNTNUMBER using the alias name Ackaccountnumber.
     * @return the ACKACCOUNTNUMBER
     */
    public String getAckaccountnumber() {
        return (String) getAttributeInternal(ACKACCOUNTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for ACKACCOUNTNUMBER using the alias name Ackaccountnumber.
     * @param value value to set the ACKACCOUNTNUMBER
     */
    public void setAckaccountnumber(String value) {
        setAttributeInternal(ACKACCOUNTNUMBER, value);
    }

    /**
     * Gets the attribute value for ACKINVESTORNAME using the alias name Ackinvestorname.
     * @return the ACKINVESTORNAME
     */
    public String getAckinvestorname() {
        return (String) getAttributeInternal(ACKINVESTORNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ACKINVESTORNAME using the alias name Ackinvestorname.
     * @param value value to set the ACKINVESTORNAME
     */
    public void setAckinvestorname(String value) {
        setAttributeInternal(ACKINVESTORNAME, value);
    }

    /**
     * Gets the attribute value for ACKINVESTORID using the alias name Ackinvestorid.
     * @return the ACKINVESTORID
     */
    public String getAckinvestorid() {
        return (String) getAttributeInternal(ACKINVESTORID);
    }

    /**
     * Sets <code>value</code> as attribute value for ACKINVESTORID using the alias name Ackinvestorid.
     * @param value value to set the ACKINVESTORID
     */
    public void setAckinvestorid(String value) {
        setAttributeInternal(ACKINVESTORID, value);
    }

    /**
     * Gets the attribute value for ACKINVESTORNPWP using the alias name Ackinvestornpwp.
     * @return the ACKINVESTORNPWP
     */
    public String getAckinvestornpwp() {
        return (String) getAttributeInternal(ACKINVESTORNPWP);
    }

    /**
     * Sets <code>value</code> as attribute value for ACKINVESTORNPWP using the alias name Ackinvestornpwp.
     * @param value value to set the ACKINVESTORNPWP
     */
    public void setAckinvestornpwp(String value) {
        setAttributeInternal(ACKINVESTORNPWP, value);
    }

    /**
     * Gets the attribute value for ACKINVESTORPASSPORT using the alias name Ackinvestorpassport.
     * @return the ACKINVESTORPASSPORT
     */
    public String getAckinvestorpassport() {
        return (String) getAttributeInternal(ACKINVESTORPASSPORT);
    }

    /**
     * Sets <code>value</code> as attribute value for ACKINVESTORPASSPORT using the alias name Ackinvestorpassport.
     * @param value value to set the ACKINVESTORPASSPORT
     */
    public void setAckinvestorpassport(String value) {
        setAttributeInternal(ACKINVESTORPASSPORT, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
