package app.bmri.scripless.model.vo.terminalmonitor;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 10 13:49:07 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ConnectTChartViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ConnectTChartViewImpl() {
    }
}
