package app.bmri.scripless.model.vo.terminalmonitor;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 10 13:49:07 ICT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ConnectTChartViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        BrokerStatus {
            public Object get(ConnectTChartViewRowImpl obj) {
                return obj.getBrokerStatus();
            }

            public void put(ConnectTChartViewRowImpl obj, Object value) {
                obj.setBrokerStatus((String)value);
            }
        }
        ,
        BeatCount {
            public Object get(ConnectTChartViewRowImpl obj) {
                return obj.getBeatCount();
            }

            public void put(ConnectTChartViewRowImpl obj, Object value) {
                obj.setBeatCount((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(ConnectTChartViewRowImpl object);

        public abstract void put(ConnectTChartViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BROKERSTATUS = AttributesEnum.BrokerStatus.index();
    public static final int BEATCOUNT = AttributesEnum.BeatCount.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ConnectTChartViewRowImpl() {
    }


    /**
     * Gets the attribute value for the calculated attribute BrokerStatus.
     * @return the BrokerStatus
     */
    public String getBrokerStatus() {
        return (String) getAttributeInternal(BROKERSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BrokerStatus.
     * @param value value to set the  BrokerStatus
     */
    public void setBrokerStatus(String value) {
        setAttributeInternal(BROKERSTATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BeatCount.
     * @return the BeatCount
     */
    public Number getBeatCount() {
        return (Number) getAttributeInternal(BEATCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BeatCount.
     * @param value value to set the  BeatCount
     */
    public void setBeatCount(Number value) {
        setAttributeInternal(BEATCOUNT, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
